### PR TITLE
Add one-by-one auto email, via desktop email app

### PR DESCRIPTION
**Pull request by maxkfranz**
@jvwong, I just decided to push a prototype.  It's very simple and it works.  If you want to make it fancier, you can play around with inquirer prompts.

Get the output: `npm run start`

Send the emails based on output: `npm run mailto`

### CODE REVIEW

**Comment by jvwong** [comment]
works great, just a small bug with the subject.

**Comment by maxkfranz** [comment]
What kind of bug?  It seemed OK when I tried it out, but I just used the single sample entry in the repo.

**Comment by jvwong** [comment]
It wasn't using the subject param. I think my email client didn't like the ampresand before the subject key

**Comment by maxkfranz** [comment]
Yeah, that first ampersand shouldn't be there.  I put the prototype together quickly, so it could use some testing before we use it to send real-user emails.

**Pull request merged**
